services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    command: npm run start:dev

  postgres:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: prisma
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: