services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: prisma
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: